apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
data:
  password: VXNlcnBhc3M= 

---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
type: Opaque
data:
  password: T3JkZXJwYXNz  
