apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bakery-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bakery-frontend
                port:
                  number: 80
