apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: malikmalikmalik/user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "boulangerie-dev-users-db.c3womcw2gy3m.eu-west-1.rds.amazonaws.com"
            - name: DB_USER
              value: "Userusername"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: password
