apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande-service
  labels:
    app: commande-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commande-service
  template:
    metadata:
      labels:
        app: commande-service
    spec:
      containers:
        - name: commande-service
          image: malikmalikmalik/order-service:latest
          ports:
            - containerPort: 8081
          env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-db-secret
                key: DB_PASSWORD
